repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix --config pyproject.toml
        language: python
        additional_dependencies: ["ruff>=0.9"]
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: ruff format --config pyproject.toml
        language: python
        additional_dependencies: ["ruff>=0.9"]
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: >-
          mypy --config-file pyproject.toml
          src tests
        language: python
        additional_dependencies: ["mypy>=1.14", "numpy>=2,<2.3", "pytest>=8"]
        require_serial: true
        types_or: [python, pyi]
        pass_filenames: false
